name = "canva-gatekeeper"
compatibility_date = "2024-07-17"
main = "worker.js"

[site]
bucket = "./" # or wherever your HTML file is
entry-point = "."

[env.production]
vars = { ADMIN_PASS = "your-secret-here" }
