name = "canva-gatekeeper"
type = "javascript"

account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-05-01"

[site]
bucket = "./"
entry-point = "."

[vars]
ADMIN_PASS = "your-secret-admin-code"  # Set your secret here
